#SERVER
server:
  port: 8081
  servlet:
    context-path: /api
      # context-path: parte di path che si frappone automaticamente tra host ed endpoint
      # http://{hostname}:{port}/{context-path}/{uri}
    # http://localhost:8081/api/....
  compression:
    enabled: true
    min-response-size: 2KB

# SPRING BOOT + DATABASE + MAIL
spring:
  application:
    name: dietiestates25

  datasource:
    url: jdbc:${DB_VENDOR}://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
        # create-drop: crea tabelle all'avvio dell'applicazione e le distrugge quando la stoppo
        # validated: confronta le entita' del progetto con le tabelle del db: se ci sono anomalie, solleva eccezione
        # none: da usare in ambiente di produzione: non viene riportata alcuna modifica al db
        # update: aggiorna il db con le tabelle/colonne nuove; non elimina colonne che non hanno piu' corrispondenza con l'entita'
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  # all'avvio dell'applicazione viene eseguito data.sql presente in resource
  sql.init.mode: always

  mail:
    # host: smtp.gmail.com
    host: ${MAIL_SMTP}
    # port: 587
    port: ${MAIL_PORT}
    # Nel caso di google lo username corrisponde all'email SENZA '@gmail.com'
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true

spring-doc:
  swagger-ui:
    enabled: true
    # http://localhost:8081/api/swagger-ui/index.html
    path: /swagger-ui/index.html
    tags-sorter: alpha
    display-request-duration: true


# LOGGING
logging:
  level:
    it.cgmconsulting: info
    org:
      springframework:
        boot: info
        security: info
    org.hibernate.orm.jdbc.bind: trace
  file.name: /Users/Public/dietiestates25/log/dietiestates25_log.txt
  # Rolling policies
  logback:
    rolling-policy:
      max-history: 7
      max-file-size: 10MB
      file-name-pattern: /Users/Public/dietiestates25/log/%d{yyyy-MM}/dietiestates25.%d{yyyy-MM-dd}.%i.txt
      total-size-cap: 1GB




# CUSTOM PROPERTIES
application:
  security:
    sonar:
      secret-token: ${SONAR_TOKEN}
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      # 12 ORE in millisecondi
      expiration: 43200000

  image:
    avatar:
      # dimensione dell'immagine in byte -> 10240 = 10kb
      size: 10240
      width: 512
      height: 512
      extensions: image/jpg,image/jpeg,image/png,image/webp
    post:
      # 50Kb
      size: 51200
      width: 600
      height: 200
      extensions: image/jpg,image/jpeg,image/webp
      imagePath: /Users/Public/dietiestates25/annuncio/images/
