version: "3.8"
services:
  api:
    build: .
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:8080"
    environment:
      # These environment variables are used by Spring Boot
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dietiestates25
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: dietiestates25
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
