version: "3.8"
services:
  api:
    build: .
    volumes:
      - ..:/workspace:cached
    ports:
      - "8081:8081"
    environment:
      # These environment variables are used by Spring Boot
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dietiestates25
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_URL=${DB_URL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SMTP=${MAIL_SMTP}
      - MAIL_USERNAME=${MAIL_USERNAME}
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: dietiestates25
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
